/**
 * PURE Safe-Exit logic — the math behind the dead-man's switch.
 *
 * `buildMarketReduceOnlyClose` turns an OPEN position into the reduce-only,
 * opposite-side, MARKET TradeIntent that FULLY closes it. This is the
 * "Claude offline" fallback the Safe-Exit panic button falls back to when no
 * fresh Claude-authored exit plan exists: a long is closed with a sell, a short
 * with a buy, and a flat position yields null (nothing to close).
 *
 * No I/O. The route (safe-exit) composes this with executeIntent. Pinned by
 * tests/lib/trading/safe-exit-business-logic.test.ts.
 */

import type { OrderSide, TradeIntent } from '@/types/fill';
import type { Position } from '@/types/position';

export interface BuildCloseInput {
  /** Idempotency key for the resulting intent (generated by the caller). */
  clientIntentId: string;
  sessionId: string;
  now: number;
}

/**
 * Build a reduce-only MARKET intent that fully closes `position`.
 *
 * A MARKET order carries no `limitPx` (the book walk fills at whatever the book
 * offers — the panic button prioritizes getting out over price). `reduceOnly` is
 * always true so the order can only shrink/close, never flip into a new
 * position. Returns null for a flat / zero-size position (nothing to exit).
 */
export function buildMarketReduceOnlyClose(
  position: Position,
  input: BuildCloseInput,
): TradeIntent | null {
  if (position.side === 'flat' || position.sz <= 0) return null;

  // Opposite side closes the exposure: long → sell, short → buy.
  const side: OrderSide = position.side === 'long' ? 'sell' : 'buy';

  return {
    clientIntentId: input.clientIntentId,
    sessionId: input.sessionId,
    coin: position.coin,
    side,
    sz: position.sz,
    // No limitPx ⇒ market order (book walk).
    reduceOnly: true,
    createdAt: input.now,
  };
}

/**
 * True when a Safe-Exit plan is FRESH enough to trust (Claude is keeping it
 * current). `updatedAtMs` is the plan's last update; `nowMs` the current time;
 * `stalenessMs` the freshness window (default 60s). A stale/absent plan means
 * "Claude offline" → the route uses the live-position market-close fallback.
 */
export function isPlanFresh(
  updatedAtMs: number | null | undefined,
  nowMs: number,
  stalenessMs = 60_000,
): boolean {
  if (updatedAtMs == null || !Number.isFinite(updatedAtMs)) return false;
  return nowMs - updatedAtMs <= stalenessMs;
}

/** Default Safe-Exit plan staleness window (ms). */
export const DEFAULT_SAFE_EXIT_STALENESS_MS = 60_000;

/**
 * True when `intent` is a valid REDUCE of `position`: same coin, and the side
 * that shrinks the live exposure (long→sell, short→buy). The panic button uses
 * this to decide whether a fresh Claude plan can still be trusted — if the
 * position flipped since the plan was armed (e.g. long→short), the stored intent
 * would now ADD exposure, so the plan must be discarded for the mechanical
 * market-close fallback instead.
 */
export function planReducesPosition(
  intent: Pick<TradeIntent, 'coin' | 'side'>,
  position: Pick<Position, 'coin' | 'side'>,
): boolean {
  if (position.side === 'flat') return false;
  if (intent.coin !== position.coin) return false;
  const reducingSide: OrderSide = position.side === 'long' ? 'sell' : 'buy';
  return intent.side === reducingSide;
}
